#!/bin/bash
set -e

WEBPACK=$APP_DIR/node_modules/.bin/webpack

pushd $APP_DIR
$WEBPACK \
	--progress \
	--colors \
	--context $APP_DIR/project \
	--config $WEBPACK_CONFIG \
	--output-path $OUTPUT
	$@
popd

if [[ ! -z $DEV_UID ]]; then
    chown -R $DEV_UID:$DEV_GID $OUTPUT
fi
