FROM builder.npm

###### Builder Boilerplate ####################################################
ADD build /usr/bin/
RUN chmod +x /usr/bin/build
CMD 'build'
###############################################################################
