RUN npm install bower
RUN ln -s {{ CONFIG.BOWER.BIN }} /usr/local/bin/

{% if CONFIG.ENV == 'PRODUCTION' %}
# Install packages - This is skipped in DEV builds because they may include
# local-third-party packages. Those packages are installed using mounted
# volumes and are not accessible to docker build.
# TODO: need to make this install configurable somehow

{% endif %}
